[package]
name = "mailer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
lettre = { version = "0.10.0-beta.2", default-features = false, features = [
  "smtp-transport",
  "tokio1-rustls-tls",
  "hostname",
  "r2d2",
  "builder",
] }
